### ISSUE TITLE
Talks section shows wrong content in specific cases

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#13]
Playing with buttons on Talks section can show wrong content.

Steps:
1. Go to page https://krzysztofszumny.com/talks
2. Reproduce cases from below

Cases to reproduce bugs:

| Case 1a | Case 1b | 
| - | - |
| 1. Click Docker OR Blockchain | 1. Click Git OR Blockchain |
| 2. Click Polish | 2. Click Polish |
| 3. Click Git | 3. Click Docker |
| 4. Click English | 4. Click English |

**Expected result:** Empty Git / Docker page (no English content)

**Actual result:** Git / Docker page with Polish content cut from bottom

Video:

https://user-images.githubusercontent.com/1151664/217507599-acb7e268-5390-4cf8-902b-b60214a26a5c.mp4

| Case 2 |
| - |
| 1. Click Git OR Docker |
| 2. Click English |
| 3. Click All OR Blockchain |
| 4. Click Polish |

**Expected result:** All page with only Polish content

**Actual result:** All page with content in both languages

Video:

https://user-images.githubusercontent.com/1151664/217507647-b3d866e7-a689-4617-b2c6-84ce68599fc9.mp4

Desktop:
Ubuntu 20.04.4 LTS: Chrome 110.0.5481.100
Windows 10: Chrome 110.0.5481.178

**Comment by lukmarcus** [comment]
| Case 3 |
| - |
| 1. Click Polish |
| 2. Click Blockchain |
| 3. Click English |
| 4. Click Git OR Docker |

Effect:
https://user-images.githubusercontent.com/1151664/217515796-6626713c-3cd8-4ea3-aa17-c390ddd2ec45.mp4

**Comment by lukmarcus** [comment]
| Case 4 |
| - |
| 1. Click English |
| 2. Click Git OR Docker |
| 3. Click Click English again |

Effect:
https://user-images.githubusercontent.com/1151664/217517444-2da189b7-7a43-4d20-8973-173ecd77884d.mp4

**Comment by noisy** [comment]
@lukmarcus really nice catch. BTW, this is a bug which would really benefit from a description with a fragment like:

expected result: ...
actual result: ...

it took me a while before I understand what this ticket is about.

**Comment by lukmarcus** [comment]
You are right, I added more information.
