### ISSUE TITLE
Companies in the "Great Companies" section are moved to the right

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#139]
Logos in the "Great Companies" section are not centered.

**Steps to reproduce**
1. In the `db.ts` file activate less or more than six companies.
2. Open the portfolio page.
3. Scroll down to the "Great Companies section".
4. Pay attention to the left and right margins of images.

**Expected behavior**
All companies are centered.

# Screenshots
### Less than six:
![obraz](https://github.com/noisy/portfolio/assets/1151664/01e7f04d-cc04-4188-83b2-e6eadeb5de63)

### More than six:
![obraz](https://github.com/noisy/portfolio/assets/1151664/8659fa60-448f-4b31-ae27-67783b34b916)

**Comment by noisy** [comment]
notes. Should be fixed.
