### ISSUE TITLE
Section 'Featured Projects' should show 3/6 or 2x2 projects

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#15]
On desktop view - 4 is not the best option for number of Featured Projects. In grid with 3 columns it would be better with 3 (one line) or 6 (two lines) projects. The other option is to use grid 2x2 but it won't look that good.

![obraz](https://user-images.githubusercontent.com/1151664/217520386-7de24477-b506-4e3d-bb85-bfab8a48bb51.png)

**Comment by noisy** [comment]
for now 6 projects will be featured. In the future this could change, but for now we can clsoe this.
