### ISSUE TITLE
Additional 'Other Project Case Studies' title on Opera and HiveProjects pages

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#30]
Page: https://krzysztofszumny.com/project/hiveprojects.io
& https://krzysztofszumny.com/project/opera-mobile

Between project description and 'Other Project Case Studies' section you can find additional 'Other Project Case Studies' title.

HiveProjects:
![obraz](https://user-images.githubusercontent.com/1151664/218048456-eec6f8bc-0009-462a-8fc6-568c7af7fb3f.png)

Opera Mobile:
![obraz](https://user-images.githubusercontent.com/1151664/218048579-c107638e-7765-432e-88d1-0455c4606375.png)

Desktop:
Firefox 109.0.1.
Chrome 110.0.5481.78.

Mobile:
Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36

**Comment by noisy** [comment]
@lukmarcus how this is different from #29?

**Comment by lukmarcus** [comment]
#29: main project, which is the "hero" of this page, is also present as "other" at the bottom of the page
#30: title of section "other projects" is double on two projects (Opera and HiveProjects)

Image helper:
![Image1](https://user-images.githubusercontent.com/1151664/218275325-6ecfa1e1-fd82-491a-85ab-7e6f411dba66.jpg)

**Comment by noisy** [comment]
@lukmarcus sorry for that question. It looks like I was already very tired when I read this ticket and asked that.
