### ISSUE TITLE
After switching to another view, website is partially scrolled.

### ISSUE THREAD

**Issue by noisy** [noisy/portfolio#5]
[Screencast from 07.02.2023 18:20:46.webm](https://user-images.githubusercontent.com/201263/217318054-f38f517d-7b3b-4b28-b1e5-b1cd9d683723.webm)

**Comment by lukmarcus** [comment]
In my opinion this should be `Priority: Major`. When you are on the bottom of the page and you click any inside link, you don't even realize page was reloaded into new content so it looks like something is wrong.
