### ISSUE TITLE
Wrong hover behavior for blog's link "How I bankrupt" in project "SpisTresci"

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#52]
There's a link to blog's post "How I bankrupt" in "SpisTresci" project's page. Thumbnail's hover behavior is different from the same's thumbnail in blog page.

Steps:
1. Open page https://krzysztofszumny.com/project/spistresci
2. Find section `Not understanding what MVP truly means`
3. Post's thumbnail is in this section

Expected effect: Hover effect is the same as on page https://krzysztofszumny.com/blog

Actual effect: Thumbnail doesn't get darker and button `Read more` is always visible.

Video help:

[Krzysztof-s-Portfolio.webm](https://user-images.githubusercontent.com/1151664/220482921-2a66d863-2524-46a9-8ef8-6d4f8ad339c1.webm)

Desktop:
Chrome 110.0.5481.100
Ubuntu 20.04.4 LTS

**Comment by noisy** [comment]
really good catch.

**Comment by noisy** [comment]
@lukmarcus I think you could try to take care of that as well.
