### ISSUE TITLE
Page favicon is static on Chrome

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#55]
Page favicon is not animated in Chrome - comparing to Firefox where it's animated.

Steps:
1. Open page https://krzysztofszumny.com/ in Chrome
2. Look at favicon on the browser's tab

Expected effect: Favicon ![](https://raw.githubusercontent.com/noisy/portfolio/master/public/favicon.ico) is animated 

Actual effect: Favicon ![image](https://user-images.githubusercontent.com/1151664/220750238-c77dfcd8-e22a-458d-b2a2-debeba69c303.png) is static

![image](https://user-images.githubusercontent.com/1151664/220749796-35b47dda-6607-4793-90b7-1fb6c77784ff.png)

Desktop:
Ubuntu 20.04.4 LTS: Chrome 110.0.5481.100
Windows 10: Chrome 110.0.5481.178

**Comment by noisy** [comment]
This is not a bug per se. In general most browsers do not support animated favicons.

https://stackoverflow.com/questions/16090206/putting-gif-image-in-favicon-not-working-on-chrome

This is reported as bug in Chrome from 2009: http://code.google.com/p/chromium/issues/detail?id=19731


That's said, this can be achieved with JS.
