### ISSUE TITLE
Video description on Talks page behaves differently depending on the page width

### ISSUE THREAD

**Issue by lukmarcus** [noisy/portfolio#62]
Descriptions of videos on Talks page don't behave correctly on different page width. Sometimes description stays on the right and goes off the screen - ie. between 636px and 766px OR 844px and 978px.

Steps:
1. Open page https://krzysztofszumny.com/talks
2. Change page width into range between 636px and 766px OR 844px and 978px

Expected effect: Description should change position under the video

Actual effect: Description stays on right of video and goes off the screen

Video

https://user-images.githubusercontent.com/1151664/221419345-3efc2d24-1c12-4209-8363-8f4a7d281b63.mp4

Desktop
Ubuntu 20.04.4 LTS Chrome 110.0.5481.100

**Comment by noisy** [comment]
@lukmarcus this issue could be tricky, but at the same time I would not be surprised if solution would be simple. If you want, you can try to fix that, but let's try to cap the max amount of time spent on that on your end to 1 hour. After that, if not solved, write down your findings here and let me know.

**Comment by noisy** [comment]
> @lukmarcus this issue could be tricky, but at the same time I would not be surprised if solution would be simple. If you want, you can try to fix that, but let's try to cap the max amount of time spent on that on your end to 1 hour. After that, if not solved, write down your findings here and let me know.

LOL. Now I see, you already created a fix for that. Somehow, I thought your PR was about something else. Great job!
